[workspace]
resolver = "2"

members = [
  "prover",
  "verifier",
  "example-workload-input",
]

exclude = [
  "example-workload-guest"
]

[workspace.package]
name = "gevulot-test"
version = "0.1.0"
edition = "2021"
